name: CI

on: 
  push:
    branches:
      - master

jobs:
  deploy-on-heroku:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Yarn install
        run: yarn

      - name: Heroku Login
        uses: actions/heroku@master
        with:
          args: container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Heroku push
        uses: actions/heroku@master
        with:
          args: container:push -a $HEROKU_APP web
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP: twin-peaks-api
  
      - name: Heroku Release
        uses: actions/heroku@master
        with:
          args: container:release -a $HEROKU_APP web
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP: twin-peaks-api
