name: CI

on: 
  push:
    branches:
      - master

jobs:
  deploy-on-heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build docker image
        uses: actions/docker/cli@master
        with:
          args: build -t $HEROKU_APP .
        env:
          HEROKU_APP: ${{ secrets.HEROKU_APP }}

      - name: Heroku Login
        uses: actions/heroku@master
        with:
          args: container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP: twin-peaks-api

      - name: Heroku push
        uses: actions/heroku@master
        with:
          args: container:push web -a $HEROKU_APP
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP: twin-peaks-api
  
      - name: Heroku Release
        uses: actions/heroku@master
        with:
          args: container:release web -a $HEROKU_APP
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP: twin-peaks-api
