name: CI

on: 
  push:
    branches:
      - master

jobs:
  deploy-on-heroku:
    runs-on: ubuntu-latest
    steps: 
    - name: Deploy to Heroku
      run: echo "Follow deployment on Heroku https://dashboard.heroku.com/apps/twin-peaks-api/activity"
